# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build-and-Unit-Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-unit-test:

    runs-on: ubuntu-latest

    steps:
    - name: Chekout Repository
      uses: actions/checkout@v4
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install npm Dependencies    
      run: npm install
    - name: Unit Test
      run: npm run test:unit
    - name: Display SoftUni UserName - @VPP88
      run: echo '@VPP88'
  ui-tests:
    runs-on: ubuntu-latest
    needs: build-and-unit-test
    steps:
    - name: Chekout Repository
      uses: actions/checkout@v4
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install npm Dependencies    
      run: npm install
    - name: Install Browsers
      run: npx playwright install
    - name: Run Application
      run: npm start &    
    - name: UI Test
      run: npm run test:ui
    - name: Display SoftUni UserName - @VPP88
      run: echo '@VPP88'    
  deploy-to-render:
      runs-on: ubuntu-latest
      needs: ui-tests
      steps:
      - uses: actions/checkout@v3
      - uses: JorgeLNJunior/render-deploy@v1.4.4
        with:
          service_id: ${{ secrets.RENDER_SERVICE_ID }}
          api_key: ${{ secrets.RENDER_API_KEY }}
          wait_deploy: true 
      - name: Display SoftUni UserName - @VPP88
        run: echo '@VPP88'    